name    'mmoll-dataprotector'
version '0.0.4'
source 'git://github.com/mmoll/puppet-dataprotector'
author 'Michael Moll'
license 'Apache License, Version 2.0'
summary 'HP Data Protector client module'
description 'Manages HP Dataprotector clients'
project_page 'http://github.com/mmoll/puppet-dataprotector'
